# Generated by Django 4.2 on 2023-04-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0002_alter_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('subject', models.TextField()),
                ('reason', models.TextField()),
            ],
        ),
    ]
