# Generated by Django 4.2 on 2023-04-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0003_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='accept',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='declane',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nots',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
