# Generated by Django 4.2 on 2023-05-04 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0004_student_accept_student_declane_student_nots'),
    ]

    operations = [
        migrations.CreateModel(
            name='prof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('photo', models.FileField(upload_to='images/')),
            ],
        ),
    ]
