# Generated by Django 4.2 on 2023-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0005_prof'),
    ]

    operations = [
        migrations.AddField(
            model_name='prof',
            name='branch',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
