# Generated by Django 4.2 on 2023-05-04 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pass', '0006_prof_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prof',
            name='branch',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='prof',
            name='username',
            field=models.EmailField(max_length=254),
        ),
    ]
